Warning, the following versions were found for celery
3.1.18
3.1.17
3.1.16
3.1.15
3.1.14
3.1.13
3.1.12
3.1.11
3.1.10
3.1.9
3.1.8
3.1.7
3.1.6
3.1.5
3.1.4
3.1.3
3.1.2
3.1.1
3.1.0
3.0.25
3.0.24
3.0.23
3.0.22
3.0.21
3.0.20
3.0.19
3.0.18
3.0.17
3.0.16
3.0.15
3.0.14
3.0.13
3.0.12
3.0.11
3.0.10
3.0.9
3.0.8
3.0.7
3.0.6
3.0.5
3.0.4
3.0.3
3.0.2
3.0.1
3.0.0
2.5.5
2.5.3
2.5.2
2.5.1
2.5.0
2.4.7
2.4.6
2.4.5
2.4.4
2.4.3
2.4.2
2.4.1
2.4.0
2.3.5
2.3.4
2.3.3
2.3.2
2.3.1
2.3.0
2.2.10
2.2.9
2.2.8
2.2.7
2.2.6
2.2.5
2.2.4
2.2.3
2.2.2
2.2.1
2.2.0
2.1.4
2.1.3
2.1.2
2.1.1
2.1.0
2.0.3
2.0.2
2.0.1
2.0.0
1.0.6
1.0.5
1.0.4
1.0.3
1.0.2
1.0.1
1.0.0
0.8.4
0.8.3
0.8.2
0.8.1
0.8.0
0.6.0
0.4.1
0.4.0
0.3.20
0.3.7
0.3.0
0.2.0
0.1.15
0.1.14
0.1.13
0.1.12
0.1.11
0.1.10
0.1.8
0.1.7
0.1.6
0.1.4
0.1.2
Using 3.1.18
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/c/celery/celery-3.1.18.tar.gz (1.2 MB) for celery.
Downloading celery (use --no-download to skip this step)
Using cached download
Unpacking celery...
done
working in /tmp/tmpOBGfD8conda_skeleton_celery-3.1.18.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

Applying patch: '/tmp/tmpOBGfD8conda_skeleton_celery-3.1.18.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpOBGfD8conda_skeleton_celery-3.1.18.tar.gz/celery-3.1.18
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
