Warning, the following versions were found for django-auth-ldap
1.2.6
1.2.5
1.2.4
1.2.3
1.2.2
1.2.1
1.2.0
1.1.8
1.1.7
1.1.6
1.1.5
1.1.4
1.1.3
1.1.2
1.1.1
1.1
1.0.19
1.0.18
1.0.17
1.0.16
1.0.15
1.0.14
1.0.13
1.0.12
1.0.11
1.0.10
Using 1.2.6
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/d/django-auth-ldap/django-auth-ldap-1.2.6.tar.gz (128 KB) for django-auth-ldap.
Downloading django-auth-ldap (use --no-download to skip this step)
Using cached download
Unpacking django-auth-ldap...
done
working in /tmp/tmpPsSZTBconda_skeleton_django-auth-ldap-1.2.6.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Applying patch: '/tmp/tmpPsSZTBconda_skeleton_django-auth-ldap-1.2.6.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpPsSZTBconda_skeleton_django-auth-ldap-1.2.6.tar.gz/django-auth-ldap-1.2.6
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
