Removing old build directory
Removing old work directory
BUILD START: fixtures-1.2.0-py27_0
Fetching package metadata: ........
Solving package specifications: .+ /home/hargup/anaconda/envs/_build/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    pbr=True)
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/setuptools/dist.py", line 268, in __init__
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/setuptools/dist.py", line 313, in fetch_build_eggs
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/pkg_resources/__init__.py", line 830, in resolve
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/pkg_resources/__init__.py", line 1075, in best_match
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/pkg_resources/__init__.py", line 1087, in obtain
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/setuptools/dist.py", line 380, in fetch_build_egg
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/setuptools/command/easy_install.py", line 617, in easy_install
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/setuptools/package_index.py", line 594, in fetch_distribution
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/setuptools/package_index.py", line 431, in find_packages
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/setuptools/package_index.py", line 765, in scan_url
  File "/home/hargup/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/setuptools/package_index.py", line 283, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/pbr/r

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-3     
    readline:   6.2-2       
    setuptools: 16.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Linking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[readline            ]|#####                                             |  11%[sqlite              ]|###########                                       |  22%[system              ]|################                                  |  33%[tk                  ]|######################                            |  44%[zlib                ]|###########################                       |  55%[python              ]|#################################                 |  66%[setuptools          ]|######################################            |  77%[pip                 ]|############################################      |  88%[      COMPLETE      ]|##################################################| 100%
Removing old work directory
Source cache directory is: /home/hargup/anaconda/conda-bld/src_cache
Found source in cache: fixtures-1.2.0.tar.gz
Extracting download
Package: fixtures-1.2.0-py27_0
source tree in: /home/hargup/anaconda/conda-bld/work/fixtures-1.2.0
Command failed: /bin/bash -x -e /home/hargup/210fs/pypi-conda-builds/recipes/fixtures/build.sh
