Warning, the following versions were found for guess_language-spirit
0.5.2
0.5.1
0.5
0.5a5
0.5a4
0.5a3
0.5a2
0.5a1
0.4a7
0.4a6
0.4a5
0.4a4
0.4a3
0.4a2
0.4a1
0.3.2
0.3.1
0.3.0
Using 0.5.2
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/g/guess_language-spirit/guess_language-spirit-0.5.2.tar.bz2 (80 KB) for guess_language-spirit.
Downloading guess_language-spirit (use --no-download to skip this step)
Using cached download
Unpacking guess_language-spirit...
done
working in /tmp/tmpxRBlNtconda_skeleton_guess_language-spirit-0.5.2.tar.bz2
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 605, in <module>
    sys.exit(main())
  File "setup.py", line 600, in main
    run_setup_hooks(config)
  File "setup.py", line 576, in run_setup_hooks
    func(config)
  File "setup.py", line 590, in default_hook
    generate_py2k(config)
  File "setup.py", line 550, in generate_py2k
    run_3to2(copied_py_files)
  File "setup.py", line 394, in run_3to2
    run_3to2_script(args)
  File "setup.py", line 379, in run_3to2_script
    proc = subprocess.Popen(["3to2"] + args, stderr=subprocess.PIPE)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Applying patch: '/tmp/tmpxRBlNtconda_skeleton_guess_language-spirit-0.5.2.tar.bz2/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpxRBlNtconda_skeleton_guess_language-spirit-0.5.2.tar.bz2/guess_language-spirit-0.5.2
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
