Using url https://pypi.python.org/packages/source/o/oauthlib/oauthlib-0.7.2.tar.gz (104 KB) for oauthlib.
Downloading oauthlib (use --no-download to skip this step)
Using cached download
Unpacking oauthlib...
done
working in /tmp/tmp7iLxx8conda_skeleton_oauthlib-0.7.2.tar.gz
Fetching package metadata: ........
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

The following NEW packages will be INSTALLED:

    numpy:      1.9.2-py27_0
    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-3     
    pyyaml:     3.11-py27_0 
    readline:   6.2-2       
    setuptools: 16.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    yaml:       0.1.4-0     
    zlib:       1.2.8-0     

Linking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[readline            ]|####                                              |   8%[sqlite              ]|########                                          |  16%[system              ]|############                                      |  25%[tk                  ]|################                                  |  33%[yaml                ]|####################                              |  41%[zlib                ]|#########################                         |  50%[numpy               ]|#############################                     |  58%[python              ]|#################################                 |  66%[pyyaml              ]|#####################################             |  75%[setuptools          ]|#########################################         |  83%[pip                 ]|#############################################     |  91%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmp7iLxx8conda_skeleton_oauthlib-0.7.2.tar.gz/pypi-distutils.patch'
pyjwt not found, trying PyJWT
2
Warning, the following versions were found for PyJWT
1.3.0
1.1.0
1.0.1
1.0.0
0.4.3
0.4.2
0.4.1
Using 1.3.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/P/PyJWT/PyJWT-1.3.0.tar.gz (60 KB) for PyJWT.
Downloading PyJWT (use --no-download to skip this step)
PyJWT-1.3.0.ta   0% |                              | ETA:  --:--:--   0.00  B/sPyJWT-1.3.0.ta  26% |########                       | ETA:  0:00:00  12.35 MB/sPyJWT-1.3.0.ta  52% |################               | ETA:  0:00:00 421.36 kB/sPyJWT-1.3.0.ta  79% |########################       | ETA:  0:00:00 622.63 kB/sPyJWT-1.3.0.ta 100% |###############################| ETA:  0:00:00 777.36 kB/sPyJWT-1.3.0.ta 100% |###############################| Time: 0:00:00 771.10 kB/s
Unpacking PyJWT...
done
working in /tmp/tmp0_EAoYconda_skeleton_PyJWT-1.3.0.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmp0_EAoYconda_skeleton_PyJWT-1.3.0.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/p/pep8-naming/pep8-naming-0.2.2.tar.gz (5 KB) for pep8-naming.
Downloading pep8-naming (use --no-download to skip this step)
pep8-naming-0.   0% |                              | ETA:  --:--:--   0.00  B/spep8-naming-0. 100% |###############################| Time: 0:00:00   7.37 MB/spep8-naming-0. 100% |###############################| Time: 0:00:00   4.94 MB/spep8-naming-0. 100% |###############################| Time: 0:00:00   3.65 MB/s
Unpacking pep8-naming...
done
working in /tmp/tmp8cSFR4conda_skeleton_pep8-naming-0.2.2.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmp8cSFR4conda_skeleton_pep8-naming-0.2.2.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/f/flake8-import-order/flake8-import-order-0.6.linux-x86_64.tar.gz (14 KB) for flake8-import-order.
Downloading flake8-import-order (use --no-download to skip this step)
flake8-import-   0% |                              | ETA:  --:--:--   0.00  B/sflake8-import- 100% |###############################| Time: 0:00:00  19.18 MB/sflake8-import- 100% |###############################| Time: 0:00:00  13.21 MB/sflake8-import- 100% |###############################| Time: 0:00:00  10.05 MB/s
Unpacking flake8-import-order...
done
working in /tmp/tmpLpus51conda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
/home/hargup/anaconda/envs/_build/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory

Applying patch: '/tmp/tmpLpus51conda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpLpus51conda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz/home
Error: command failed: /home/hargup/anaconda/envs/_build/bin/python setup.py install
