Warning, the following versions were found for passlib
1.6.2
1.6.1
1.6
1.5.3
1.5.2
1.5.1
1.5
1.4
1.3.1
1.3.0
Using 1.6.2
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/passlib/passlib-1.6.2.tar.gz (399 KB) for passlib.
Downloading passlib (use --no-download to skip this step)
Using cached download
Unpacking passlib...
done
working in /tmp/tmp9_pjTDconda_skeleton_passlib-1.6.2.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.



Applying patch: '/tmp/tmp9_pjTDconda_skeleton_passlib-1.6.2.tar.gz/pypi-distutils.patch'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 244, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 258, in execute
    pypi.main(args, parser)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 390, in main
    get_package_metadata(args, package, d, data)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 626, in get_package_metadata
    in pkginfo['tests_require']]))
TypeError: sequence item 0: expected string, NoneType found
