There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
Removing old build directory
Removing old work directory
BUILD START: pyodbc-3.0.10-py27_0
Fetching package metadata: ......
Solving package specifications: .There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
+ /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
running install
running bdist_egg
running egg_info
writing pyodbc.egg-info/PKG-INFO
writing top-level names to pyodbc.egg-info/top_level.txt
writing dependency_links to pyodbc.egg-info/dependency_links.txt
reading manifest file 'pyodbc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'tests/*'
warning: no files found matching 'README.rst'
writing manifest file 'pyodbc.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'pyodbc' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/home
creating build/temp.linux-x86_64-2.7/home/ubuntu
creating build/temp.linux-x86_64-2.7/home/ubuntu/miniconda
creating build/temp.linux-x86_64-2.7/home/ubuntu/miniconda/conda-bld
creating build/temp.linux-x86_64-2.7/home/ubuntu/miniconda/conda-bld/work
creating build/temp.linux-x86_64-2.7/home/ubuntu/miniconda/conda-bld/work/pyodbc-3.0.10
creating build/temp.linux-x86_64-2.7/home/ubuntu/miniconda/conda-bld/work/pyodbc-3.0.10/src
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPYODBC_VERSION=3.0.10 -DPYODBC_UNICODE_WIDTH=4 -DSQL_WCHART_CONVERT=1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include -I/home/ubuntu/miniconda/envs/_build/include/python2.7 -c /home/ubuntu/miniconda/conda-bld/work/pyodbc-3.0.10/src/pyodbcmodule.cpp -o build/temp.linux-x86_64-2.7/home/ubuntu/miniconda/conda-bld/work/pyodbc-3.0.10/src/pyodbcmodule.o -Wno-write-strings
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-3     
    readline:   6.2-2       
    setuptools: 16.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Linking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[readline            ]|#####                                             |  11%[sqlite              ]|###########                                       |  22%[system              ]|################                                  |  33%[tk                  ]|######################                            |  44%[zlib                ]|###########################                       |  55%[python              ]|#################################                 |  66%[setuptools          ]|######################################            |  77%[pip                 ]|############################################      |  88%[      COMPLETE      ]|##################################################| 100%
Removing old work directory
Source cache directory is: /home/ubuntu/miniconda/conda-bld/src_cache
Found source in cache: pyodbc-3.0.10.tar.gz
Extracting download
Package: pyodbc-3.0.10-py27_0
source tree in: /home/ubuntu/miniconda/conda-bld/work/pyodbc-3.0.10
Command failed: /bin/bash -x -e /home/ubuntu/pypi-conda-builds/recipes/pyodbc/build.sh
