Warning, the following versions were found for python-social-auth
0.2.10
0.2.9
0.2.7
0.2.6
0.2.5
0.2.4
0.2.3
0.2.2
0.2.1
0.2.0
0.1.26
0.1.25
0.1.24
0.1.23
0.1.22
0.1.21
0.1.20
0.1.19
0.1.18
0.1.17
0.1.16
0.1.15
0.1.14
0.1.13
0.1.12
0.1.11
0.1.10
0.1.9
0.1.8
0.1.7
0.1.6
0.1.5
0.1.4
0.1.3
0.1.2
0.1.1
0.1.0
Using 0.2.10
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/python-social-auth/python-social-auth-0.2.10.tar.gz (243 KB) for python-social-auth.
Downloading python-social-auth (use --no-download to skip this step)
Using cached download
Unpacking python-social-auth...
done
working in /tmp/tmp9gZDd0conda_skeleton_python-social-auth-0.2.10.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Applying patch: '/tmp/tmp9gZDd0conda_skeleton_python-social-auth-0.2.10.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmp9gZDd0conda_skeleton_python-social-auth-0.2.10.tar.gz/python-social-auth-0.2.10
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
