Using url https://pypi.python.org/packages/source/p/python-social-auth/python-social-auth-0.2.9.tar.gz (237 KB) for python-social-auth.
Downloading python-social-auth (use --no-download to skip this step)
Using cached download
Unpacking python-social-auth...
done
working in /tmp/tmpGFY5Jvconda_skeleton_python-social-auth-0.2.9.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmpGFY5Jvconda_skeleton_python-social-auth-0.2.9.tar.gz/pypi-distutils.patch'
pyjwt not found, trying PyJWT
0
Warning, the following versions were found for PyJWT
1.3.0
1.1.0
1.0.1
1.0.0
0.4.3
0.4.2
0.4.1
Using 1.3.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/P/PyJWT/PyJWT-1.3.0.tar.gz (60 KB) for PyJWT.
Downloading PyJWT (use --no-download to skip this step)
Using cached download
Unpacking PyJWT...
done
working in /tmp/tmpkYMQtdconda_skeleton_PyJWT-1.3.0.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmpkYMQtdconda_skeleton_PyJWT-1.3.0.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/p/pep8-naming/pep8-naming-0.2.2.tar.gz (5 KB) for pep8-naming.
Downloading pep8-naming (use --no-download to skip this step)
Using cached download
Unpacking pep8-naming...
done
working in /tmp/tmp3pfozAconda_skeleton_pep8-naming-0.2.2.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmp3pfozAconda_skeleton_pep8-naming-0.2.2.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/f/flake8-import-order/flake8-import-order-0.6.linux-x86_64.tar.gz (14 KB) for flake8-import-order.
Downloading flake8-import-order (use --no-download to skip this step)
Using cached download
Unpacking flake8-import-order...
done
working in /tmp/tmpQDHQ3Fconda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
/home/ubuntu/miniconda/envs/_build/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory

Applying patch: '/tmp/tmpQDHQ3Fconda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpQDHQ3Fconda_skeleton_flake8-import-order-0.6.linux-x86_64.tar.gz/home
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
