Package search: {'_pypi_ordering': False, 'version': '0.5.0', 'name': 'testscenarios', 'summary': 'Testscenarios, a pyunit extension for dependency injection'}
Fetching package metadata: ....
Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting testscenarios==0.5.0
  Downloading http://localhost/packages/2.7/t/testscenarios/testscenarios-0.5.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages (from testscenarios==0.5.0)
Collecting testtools (from testscenarios==0.5.0)
  Downloading http://localhost/packages/2.7/t/testtools/testtools-1.8.0-py2.py3-none-any.whl (160kB)
Requirement already satisfied (use --upgrade to upgrade): pip in /home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages (from pbr>=0.11->testscenarios==0.5.0)
Collecting traceback2 (from testtools->testscenarios==0.5.0)
  Downloading http://localhost/packages/3.4/t/traceback2/traceback2-1.4.0-py2.py3-none-any.whl
Collecting extras (from testtools->testscenarios==0.5.0)
  Downloading http://localhost/packages/source/e/extras/extras-0.0.3.tar.gz
Collecting unittest2>=1.0.0 (from testtools->testscenarios==0.5.0)
  Downloading http://localhost/packages/3.4/u/unittest2/unittest2-1.0.1-py2.py3-none-any.whl (95kB)
Collecting python-mimeparse (from testtools->testscenarios==0.5.0)
  Downloading http://localhost/packages/source/p/python-mimeparse/python-mimeparse-0.1.4.tar.gz
Collecting linecache2 (from traceback2->testtools->testscenarios==0.5.0)
  Downloading http://localhost/packages/3.5/l/linecache2/linecache2-1.0.0-py2.py3-none-any.whl
Collecting argparse (from unittest2>=1.0.0->testtools->testscenarios==0.5.0)
  Downloading http://localhost/packages/2.7/a/argparse/argparse-1.3.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages (from unittest2>=1.0.0->testtools->testscenarios==0.5.0)
Installing collected packages: linecache2, traceback2, extras, argparse, unittest2, python-mimeparse, testtools, testscenarios
  Running setup.py install for extras
  Running setup.py install for python-mimeparse
Successfully installed argparse-1.3.0 extras-0.0.3 linecache2-1.0.0 python-mimeparse-0.1.4 testscenarios-0.5.0 testtools-1.8.0 traceback2-1.4.0 unittest2-1.0.1
Fetching package metadata: ....

Package plan for package removal in environment /home/ubuntu/miniconda/envs/_pipbuild_:

The following packages will be REMOVED:

    openssl:    1.0.1k-1    
    pip:        7.0.1-py27_0
    python:     2.7.10-0    
    readline:   6.2-2       
    setuptools: 17.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Unlinking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[pip                 ]|#####                                             |  11%[python              ]|###########                                       |  22%[readline            ]|################                                  |  33%[setuptools          ]|######################                            |  44%[sqlite              ]|###########################                       |  55%[system              ]|#################################                 |  66%[tk                  ]|######################################            |  77%[zlib                ]|############################################      |  88%[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Creating standard recipe for testscenarios-0.5.0
Error: directory already exists: ./testscenarios

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install testscenarios==0.5.0
Getting dependencies...
package = testscenarios
   dependencies = ['pbr', 'testtools']
Creating standard recipe for testtools
Converting recipe in /home/ubuntu/pypi-conda-builds/testtools
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 75, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 361, in execute
    build_package(package, version)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 315, in build_package
    build_package(depend)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 303, in build_package
    dependencies = convert_recipe(directory, package)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 198, in convert_recipe
    d['homeurl'] = meta['about']['home']
KeyError: 'home'
