Warning, the following versions were found for wsgiref
0.1.2
0.1.1
0.1
Using 0.1.2
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/w/wsgiref/wsgiref-0.1.2.zip (36 KB) for wsgiref.
Downloading wsgiref (use --no-download to skip this step)
Using cached download
Unpacking wsgiref...
done
working in /tmp/tmprgcqdyconda_skeleton_wsgiref-0.1.2.zip
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

---------------------------------------------------------------------------
This script requires setuptools version 0.6b3 to run (even to display
help).  I will attempt to download it for you (from
http://cheeseshop.python.org/packages/2.7/s/setuptools/), but
you may need to enable firewall access for this script first.
I will start the download in 15 seconds.

(Note: if this machine does not have network access, please obtain the file

   http://cheeseshop.python.org/packages/2.7/s/setuptools/setuptools-0.6b3-py2.7.egg

and place it in this directory before rerunning this script.)
---------------------------------------------------------------------------
Downloading http://cheeseshop.python.org/packages/2.7/s/setuptools/setuptools-0.6b3-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    ez_setup.use_setuptools()
  File "/tmp/tmprgcqdyconda_skeleton_wsgiref-0.1.2.zip/wsgiref-0.1.2/ez_setup/__init__.py", line 70, in use_setuptools
    egg = download_setuptools(version, download_base, to_dir, download_delay)
  File "/tmp/tmprgcqdyconda_skeleton_wsgiref-0.1.2.zip/wsgiref-0.1.2/ez_setup/__init__.py", line 124, in download_setuptools
    src = urllib2.urlopen(url)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

Applying patch: '/tmp/tmprgcqdyconda_skeleton_wsgiref-0.1.2.zip/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmprgcqdyconda_skeleton_wsgiref-0.1.2.zip/wsgiref-0.1.2
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
